name: Build TWRP for gta4lve

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Build Tools
      run: |
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Install Repo Tool
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync TWRP Source
      run: |
        mkdir twrp
        cd twrp
        git config --global user.name "faksgis"
        git config --global user.email "a01096901125z@gmail.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
        repo sync -j$(nproc) --force-sync

    - name: Insert Device Tree
      run: |
        mkdir -p twrp/device/samsung/gta4lve
        cp -r * twrp/device/samsung/gta4lve/ || true

    - name: Building TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_gta4lve-eng
        make recoveryimage -j$(nproc)

    - name: Upload TWRP Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP_Build_gta4lve
        path: twrp/out/target/product/gta4lve/recovery.*
