name: Build TWRP for gta4lve

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Missing Host Libraries
      run: |
        sudo apt-get update || true
        sudo apt-get install -y git libtinfo5 libncurses5 || true
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5 || true
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5 || true

    - name: Sync TWRP Source
      run: |
        # تنزيل وإعداد أداة repo في مسار محلي مضمون داخل الخطوة
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

        mkdir twrp
        cd twrp
        git config --global user.name "faksgis"
        git config --global user.email "a01096901125z@gmail.com"
        
        # بدء التحميل
        ~/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
        ~/bin/repo sync -j$(nproc) --force-sync --no-clone-bundle --current-branch

    - name: Insert Device Tree
      run: |
        mkdir -p twrp/device/samsung/gta4lve
        cp -r * twrp/device/samsung/gta4lve/ || true
        rm -rf twrp/device/samsung/gta4lve/twrp
        rm -rf twrp/device/samsung/gta4lve/.git
        rm -rf twrp/device/samsung/gta4lve/.github
        echo "BOARD_AVB_ENABLE := false" >> twrp/device/samsung/gta4lve/BoardConfig.mk
        mkdir -p twrp/device/samsung/gta4lve/prebuilt
        touch twrp/device/samsung/gta4lve/prebuilt/kernel

    - name: Building TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_gta4lve-eng
        make recoveryimage -j$(nproc)

    - name: Upload TWRP Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TWRP_Build_gta4lve
        path: twrp/out/target/product/gta4lve/recovery.*
